'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

export default function AdminFraudDashboard() {
  const [flags, setFlags] = useState<any[]>([]);
  const [summary, setSummary] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  
  const [filterStatus, setFilterStatus] = useState('');
  const [filterType, setFilterType] = useState('');

  const router = useRouter();

  const fetchFlags = async () => {
    setLoading(true);
    try {
      let query = [];
      if (filterStatus) query.push(`status=${filterStatus}`);
      if (filterType) query.push(`entityType=${filterType}`);
      const qs = query.length > 0 ? `?${query.join('&')}` : '';

      const res = await fetch(`/api/admin/fraud/flags${qs}`);
      if (res.status === 401 || res.status === 403) {
        router.push('/admin/login');
        return;
      }
      const data = await res.json();
      if (data.success) {
        setFlags(data.flags);
        if (!filterStatus && !filterType) {
          setSummary(data.summary);
        }
      } else {
        setError(data.error);
      }
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchFlags();
  }, [filterStatus, filterType]);

  if (loading && !summary) return <div className="p-6 text-center text-gray-500">Loading Risk Signals...</div>;
  if (error) return <div className="p-6 text-center text-red-500">{error}</div>;

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div className="mb-6 border-b pb-4">
        <h1 className="text-2xl font-bold">Fraud & Risk Monitoring</h1>
        <p className="text-sm text-gray-500 mt-1">Review deterministic risk signals generated by the platform.</p>
      </div>

      {summary && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          <div className="bg-white p-4 rounded-lg border shadow-sm text-center">
            <h3 className="text-sm font-semibold text-gray-500">OPEN</h3>
            <div className="text-2xl font-bold text-red-600">{summary.OPEN}</div>
          </div>
          <div className="bg-white p-4 rounded-lg border shadow-sm text-center">
            <h3 className="text-sm font-semibold text-gray-500">UNDER REVIEW</h3>
            <div className="text-2xl font-bold text-yellow-600">{summary.UNDER_REVIEW}</div>
          </div>
          <div className="bg-white p-4 rounded-lg border shadow-sm text-center">
            <h3 className="text-sm font-semibold text-gray-500">RESOLVED</h3>
            <div className="text-2xl font-bold text-green-600">{summary.RESOLVED}</div>
          </div>
          <div className="bg-white p-4 rounded-lg border shadow-sm text-center">
            <h3 className="text-sm font-semibold text-gray-500">DISMISSED</h3>
            <div className="text-2xl font-bold text-gray-400">{summary.DISMISSED}</div>
          </div>
        </div>
      )}

      <div className="flex gap-4 mb-4">
        <select 
          className="border rounded px-3 py-2 text-sm bg-white"
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
        >
          <option value="">All Statuses</option>
          <option value="OPEN">Open</option>
          <option value="UNDER_REVIEW">Under Review</option>
          <option value="RESOLVED">Resolved</option>
          <option value="DISMISSED">Dismissed</option>
        </select>
        
        <select 
          className="border rounded px-3 py-2 text-sm bg-white"
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
        >
          <option value="">All Entity Types</option>
          <option value="CUSTOMER">Customer</option>
          <option value="VENDOR">Vendor</option>
          <option value="BOOKING">Booking</option>
          <option value="PAYMENT">Payment</option>
        </select>
      </div>

      <div className="bg-white shadow-sm border rounded-lg overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50 text-xs font-semibold text-gray-500 uppercase tracking-wider">
            <tr>
              <th className="px-6 py-3 text-left">Date</th>
              <th className="px-6 py-3 text-left">Entity</th>
              <th className="px-6 py-3 text-left">Category & Severity</th>
              <th className="px-6 py-3 text-left">Status</th>
              <th className="px-6 py-3 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-100 text-sm">
            {flags.length === 0 ? (
              <tr>
                <td colSpan={5} className="px-6 py-8 text-center text-gray-500">
                  No risk flags found.
                </td>
              </tr>
            ) : (
              flags.map((flag) => (
                <tr key={flag.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap text-gray-500 text-xs">
                    {new Date(flag.created_at).toLocaleString()}
                  </td>
                  <td className="px-6 py-4">
                    <div className="font-bold">{flag.entity_type}</div>
                    <div className="font-mono text-xs text-gray-400 mt-1" title={flag.entity_id}>...{flag.entity_id.substring(28)}</div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="font-medium text-gray-900">{flag.risk_category}</div>
                    <span className={`inline-block mt-1 px-2 py-0.5 text-[10px] rounded-full font-bold ${
                      flag.severity === 'CRITICAL' ? 'bg-red-200 text-red-900' :
                      flag.severity === 'HIGH' ? 'bg-orange-100 text-orange-800' :
                      flag.severity === 'MEDIUM' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-blue-100 text-blue-800'
                    }`}>
                      {flag.severity}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <span className={`px-2 py-1 text-xs rounded-full font-bold ${
                      flag.status === 'OPEN' ? 'bg-red-100 text-red-800' :
                      flag.status === 'UNDER_REVIEW' ? 'bg-yellow-100 text-yellow-800' :
                      flag.status === 'RESOLVED' ? 'bg-green-100 text-green-800' :
                      'bg-gray-100 text-gray-800'
                    }`}>
                      {flag.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <Link href={`/admin/fraud/${flag.id}`} className="text-indigo-600 hover:text-indigo-900 text-sm font-medium">
                      Review &rarr;
                    </Link>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
