const fs = require('fs');
const path = require('path');

const API_DIR = path.join(__dirname, '../src/app/api');
const OUT_FILE = path.join(__dirname, '../docs/openapi.json');

const openapi = {
  openapi: "3.0.0",
  info: {
    title: "WedWithMe REST API",
    version: "1.0.0",
    description: "Autogenerated OpenAPI specification for the WedWithMe Next.js Backend."
  },
  servers: [
    { url: "/api", description: "Local API Environment" }
  ],
  paths: {},
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT"
      }
    }
  }
};

function determineTag(routePath) {
  if (routePath.includes('/admin/')) return 'Admin';
  if (routePath.includes('/customer/')) return 'Customer';
  if (routePath.includes('/vendor/')) return 'Vendor';
  if (routePath.includes('/auth/')) return 'Authentication';
  return 'General';
}

function scanApiDirectory(dir) {
  const files = fs.readdirSync(dir);

  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      scanApiDirectory(fullPath);
    } else if (file === 'route.ts') {
      const content = fs.readFileSync(fullPath, 'utf8');
      
      // Compute the endpoint path relative to /api/
      let endpointPath = fullPath.substring(API_DIR.length).replace(/\\/g, '/');
      endpointPath = endpointPath.replace(/\/route\.ts$/, '');
      if (endpointPath === '') endpointPath = '/';

      // Convert Next.js dynamic routes [id] to OpenAPI {id}
      endpointPath = endpointPath.replace(/\[([^\]]+)\]/g, '{$1}');

      const methods = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];
      const pathItem = {};
      const tag = determineTag(endpointPath);

      for (const method of methods) {
        if (content.includes(`export async function ${method}`)) {
          pathItem[method.toLowerCase()] = {
            summary: `${method} ${endpointPath}`,
            tags: [tag],
            responses: {
              "200": { description: "Successful response" },
              "401": { description: "Unauthorized" },
              "500": { description: "Internal Server Error" }
            }
          };

          // Check if auth is required
          if (content.includes('requireAnyRole') || content.includes('verifyAdminRole') || content.includes('verifyToken')) {
            pathItem[method.toLowerCase()].security = [{ bearerAuth: [] }];
          }

          // Extract path parameters
          const matches = endpointPath.match(/\{([^}]+)\}/g);
          if (matches) {
            pathItem[method.toLowerCase()].parameters = matches.map(m => ({
              name: m.replace(/[{}]/g, ''),
              in: 'path',
              required: true,
              schema: { type: 'string' }
            }));
          }
        }
      }

      if (Object.keys(pathItem).length > 0) {
        openapi.paths[endpointPath] = pathItem;
      }
    }
  }
}

console.log('Scanning Next.js API routes to generate OpenAPI spec...');
scanApiDirectory(API_DIR);

if (!fs.existsSync(path.dirname(OUT_FILE))) {
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
}

fs.writeFileSync(OUT_FILE, JSON.stringify(openapi, null, 2), 'utf8');
console.log(`OpenAPI specification generated at ${OUT_FILE}`);
